# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         GPS-Lowrance
version:      0.21
version_from: lib/GPS/Lowrance.pm
installdirs:  site
requires:
    Carp::Assert:                  0
    GD:                            0
    Geo::Coordinates::DecimalDegrees: 0
    Geo::Coordinates::UTM:         0.02
    GPS::Lowrance::LSI:            0.23
    GPS::Lowrance::Trail:          0.4
    Parse::Binary::FixedFormat:    0.02
    XML::Generator:                0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
