--- #YAML:1.0
name: GPS-Lowrance
version: 0.31
author:
  - Robert Rothenberg <rrwo at cpan.org>
abstract: Connect to Lowrance and Eagle GPS devices
license: perl
requires:
  Carp::Assert: 0
  GPS::Lowrance::LSI: 0.23
  Parse::Binary::FixedFormat: 0.02
  perl: 5.6.1
recommends:
  Device::SerialPort: 0
  GD: 0
  GD::Convert: 0
  GPS::Lowrance::Trail: 0.42
  Geo::Coordinates::DecimalDegrees: 0
  Geo::Coordinates::UTM: 0
  Win32::SerialPort: 0
  XML::Generator: 0
provides: {}
generated_by: Module::Build version 0.24
